### ISSUE TITLE
when generating a double Helix gear with more than 10deg Helix angle the gears do not fit anymore

### ISSUE THREAD

**Issue by sofiha-sven** [CenturySturgeon/GF-Gear-Generator#8]
Hi there, first I want to say thank you for your work. I was really glad to find something like this.

When I generate a standard gear with this settings everything is as axpected:

![grafik](https://github.com/user-attachments/assets/ba057190-0851-4b96-87b9-6dfc98f7f1dc)

When I create a helical gear with these settings everything is still fine:

![grafik](https://github.com/user-attachments/assets/bff90742-175e-449a-80e1-0f83e6b01ffc)

![grafik](https://github.com/user-attachments/assets/d007ab32-ddd9-4637-a180-a2abc82a3cab)

I display the spur gear and the helical gear on top of each other, so this is expected. The line of the teeth do match.

If I switch to this settings:

![grafik](https://github.com/user-attachments/assets/82691b71-28fe-4818-9c32-4428502c2368)

The result locks like this:

![grafik](https://github.com/user-attachments/assets/2bbc286f-124e-490d-8cdc-761f32452b45)

You can clearly see that the gear got somehow larger which is unexpected.

**Comment by CenturySturgeon** [comment]
Hi @sofiha-sven, this works as expected and is not an issue. You see the setting you're referring to determines the helical system under which the gear will be designed, you can read more about them [here](https://www.stlgears.com/theory#helical_systems).

In summary, the radial helical system (the one that works as you expected) is great for 3D printing since it keeps the spur gear dimensions; with the downside of not being able to manufacture with standard methods/cutters. The normal helical system changes the dimensions/geometry when compared to a spur gear, but it can be fabricated with commonly used procedures.

**Comment by sofiha-sven** [comment]
@CenturySturgeon Thank you very much for pointing that out. I guess I will have to dig more into the basics.
